# ==========================================
# 🤖 自动生成的连招剧本 (支持多重别名版)
# ==========================================

TEAM_CONFIG = {
    1: "Aemeath", # 爱弥斯
    2: "Moning", # 莫宁
    3: "Lynae", # 琳奈
}

INITIAL_CHAR_INDEX = 1

OPENER_SCRIPT =[
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "intro", "next_char": 2, "desc": "切-莫宁"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "Z1", "variant": "heavy_1"},
    {"type": "ult", "desc": "R2", "variant": "2"},
    {"type": "basic", "desc": "A2", "variant": "2"},
    {"type": "basic", "desc": "A2", "variant": "2"},
    {"type": "basic", "desc": "A2", "variant": "2"},
    {"type": "skill", "desc": "E2", "variant": "2"},
    {"type": "basic", "desc": "Z2", "variant": "heavy_2"},
    {"type": "echo", "desc": "Q"},
    {"type": "intro", "next_char": 3, "desc": "切-琳奈"},
    {"type": "ult", "desc": "R"},
    {"type": "skill", "desc": "E"},
    {"type": "intro", "next_char": 1, "desc": "切-爱弥斯"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "intro", "next_char": 3, "desc": "切-琳奈"},
    {"type": "basic", "desc": "Z2", "variant": "heavy_2"},
    {"type": "basic", "desc": "A2", "variant": "2"},
    {"type": "basic", "desc": "A2", "variant": "2"},
    {"type": "basic", "desc": "A2", "variant": "2"},
    {"type": "basic", "desc": "A3", "variant": "3"},
    {"type": "echo", "desc": "Q"},
    {"type": "intro", "next_char": 1, "desc": "切-爱弥斯"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "skill", "desc": "F", "variant": "forte"},
    {"type": "echo", "desc": "Q"},
    {"type": "ult", "desc": "R"},
    {"type": "skill", "desc": "E"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "skill", "desc": "E"},
    {"type": "basic", "desc": "Z", "variant": "heavy"},
    {"type": "ult", "desc": "R"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "intro", "next_char": 2, "desc": "变奏-莫宁"},
]

LOOP_SCRIPT = [
    {"type": "intro", "next_char": 2, "desc": "切-莫宁"},
    {"type": "ult", "desc": "R"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "skill", "desc": "E"},
    {"type": "basic", "desc": "Z", "variant": "heavy"},
    {"type": "echo", "desc": "Q"},
    {"type": "intro", "next_char": 3, "desc": "切-琳奈"},
    {"type": "ult", "desc": "R"},
    {"type": "skill", "desc": "E"},
    {"type": "intro", "next_char": 1, "desc": "切-爱弥斯"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "intro", "next_char": 3, "desc": "切-琳奈"},
    {"type": "basic", "desc": "Z", "variant": "heavy"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "echo", "desc": "Q"},
    {"type": "intro", "next_char": 1, "desc": "切-爱弥斯"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "skill", "desc": "F", "variant": "forte"},
    {"type": "echo", "desc": "Q"},
    {"type": "ult", "desc": "R"},
    {"type": "skill", "desc": "E"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "skill", "desc": "E"},
    {"type": "basic", "desc": "Z", "variant": "heavy"},
    {"type": "ult", "desc": "R"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
    {"type": "basic", "desc": "A"},
]
