# ==========================================
# 🤖 自动生成的泛式连招剧本
# ==========================================

TEAM_CONFIG = {
    1: "Aemeath", # 爱弥斯
    2: "Moning", # 莫宁
    3: "Lynae", # 琳奈
}

INITIAL_CHAR_INDEX = 1

OPENER_SCRIPT =[
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "variant": "heavy", "desc": "Z 重击"},
    {"type": "ult", "desc": "R 大招"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "skill", "desc": "E 技能"},
    {"type": "basic", "variant": "heavy", "desc": "Z 重击"},
    {"type": "echo", "desc": "Q 声骸"},
    {"type": "ult", "desc": "R 大招"},
    {"type": "skill", "desc": "E 技能"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "variant": "heavy", "desc": "Z 重击"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "echo", "desc": "Q 声骸"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "skill", "variant": "forte", "desc": "F 处决"},
    {"type": "echo", "desc": "Q 声骸"},
    {"type": "ult", "desc": "R 大招"},
    {"type": "skill", "desc": "E 技能"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "skill", "desc": "E 技能"},
    {"type": "basic", "variant": "heavy", "desc": "Z 重击"},
    {"type": "ult", "desc": "R 大招"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
]

LOOP_SCRIPT = [
    {"type": "ult", "desc": "R 大招"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "skill", "desc": "E 技能"},
    {"type": "basic", "variant": "heavy", "desc": "Z 重击"},
    {"type": "echo", "desc": "Q 声骸"},
    {"type": "ult", "desc": "R 大招"},
    {"type": "skill", "desc": "E 技能"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "variant": "heavy", "desc": "Z 重击"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "echo", "desc": "Q 声骸"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "skill", "variant": "forte", "desc": "F 处决"},
    {"type": "echo", "desc": "Q 声骸"},
    {"type": "ult", "desc": "R 大招"},
    {"type": "skill", "desc": "E 技能"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "skill", "desc": "E 技能"},
    {"type": "basic", "variant": "heavy", "desc": "Z 重击"},
    {"type": "ult", "desc": "R 大招"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
    {"type": "basic", "desc": "A 普攻"},
]
